### ISSUE TITLE
Vectors get squashed

### ISSUE THREAD

**Issue by robbiehudson** [setphen/WrappedLayout#1]
I found a bug where vectors would get squashed.

Expected behaviour:

- Vectors keep their size and get aligned (and wrapped if needed)

Actual behaviour:

- Vectors are squashed

See the Loom here: https://www.loom.com/share/a155d8831eb24314a58f08e07b4a1458

Happy to provide a Figma file if useful!

**Comment by setphen** [comment]
Thanks for the video explanation. I had not tested my plugin with group nodes, only frames and vectors as direct descendants. I'll look into it!

**Comment by setphen** [comment]
Turns out group nodes had nothing to do with it. When the parent frame is resized, I wasn't accounting for the constraints of the children. I pushed a fix – let me know if that solves it for you, thanks.

**Comment by robbiehudson** [comment]
I can confirm this is now fixed, thanks!
